extensions={
    'Image':['.jpeg','.jpg','.gif','.tiff','png'],
    'Audio':['.wav','.mp3','.aiff','.m4a'],
    'Docs':['.txt','.rtf','.pdf','.doc','.docx'],
    'Videos':['.mpeg','.mpg','.avi','.mp4','.mov'],
    'Spreadsheets':['.xls','.xlsx','.ppt','.pptx','.ods'],
    'Compressed':['.zip','.rar','.7z','.tar','.gz'],
    'Executables':['.exe','.app','.elf','.bat'],   
    'Torrents':['.torrent','.srt'],   
}